fos_rest:
    param_fetcher_listener:  true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/api, fallback_format: json, priorities: [ json ] }
            - { path: ^/, fallback_format: html, priorities: [ html ] }

    view:
      view_response_listener: force
